config/routes.rb
TheDish::Application.routes.draw do
  root 'welcome#index'

  resources :restaurants, only: [:new, :create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end

    get 'search', on: :collection
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true

  def self.search(search)
    num_terms = search.split.length
    query = (['name LIKE ?'] * num_terms).join(' AND ')
    Restaurant.where([query] + search.split.map { |term| "%#{term}%" })
  end

  def display_address
    "#{street_address}, #{city}, #{state}"
  end

  def score
    if vote_count == 0
      return "No score yet..."
    else
      "#{(fresh_votes.to_f / vote_count * 100).round}%"
    end
  end

  def vote_count
    fresh_votes + rotten_votes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def search
    @search = params[:search]
    @restaurants = Restaurant.search(@search)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def upvote
    restaurant = Restaurant.find(params[:id])
    restaurant.increment!(:fresh_votes)

    redirect_to restaurant
  end

  def downvote
    restaurant = Restaurant.find(params[:id])
    restaurant.increment!(:rotten_votes)

    redirect_to restaurant
  end

  private

  def restaurant_params
    params.required(:restaurant)
      .permit(
        :name,
        :street_address,
        :city,
        :state
      )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheDish</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/new.html.haml
%h1.center Add a New Restaurant

= form_for @restaurant do |f|
  = f.label :name, 'Name:'
  = f.text_field :name
  %br
  = f.label :street_address, 'Street Address:'
  = f.text_field :street_address
  %br
  = f.label :city, 'City:'
  = f.text_field :city
  %br
  = f.label :state, 'State:'
  = f.text_field :state
  %br
  %br
  = f.submit 'Add Restaurant'

app/views/restaurants/search.html.haml
%h1= "Search Results for '#{@search}'"

%ul
  - @restaurants.each do |restaurant|
    %li= link_to "#{restaurant.name}", restaurant
    %br

%h3 Don't see what you're looking for?
= link_to "Add a New Restaurant", new_restaurant_path(@restaurant)

app/views/restaurants/show.html.haml
%h1= @restaurant.name

= @restaurant.display_address

%h1= @restaurant.score
= "#{@restaurant.vote_count} votes"

%br
%br

Would you recommend this restaurant?
= link_to "Yes", upvote_restaurant_path(@restaurant), method: :post
= link_to "No", downvote_restaurant_path(@restaurant), method: :post

app/views/welcome/index.html.haml
%h1 Welcome to The Dish!

= form_tag search_restaurants_path, method: 'get' do
  = label_tag :search, 'Search for a restaurant:'
  = text_field_tag :search
  = submit_tag 'Search'
  